server:
  port: 8080
  servlet:
    context-path: /v1.0
spring:
  application:
    name: api-prices
    version: develop
  datasource:
    url: jdbc:h2:mem:prices_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
     hibernate.format_sql: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  batch:
    jdbc:
      initialize-schema: always
azure:
  application-insights: #appi-ti-dev
    instrumentation-key: c8eb404e-8052-4e45-afa8-b2438f6d19eb
apigee:
  url: https://colsubsidio-test.apigee.net
  path:
    auth: /oauth/client_credential/accesstoken
    logger: /api/v1/tecnologia/logger
  token:
    url: /oauth/client_credential/accesstoken
    clienteId: cmnGMnGPVKLJwWLfWxqFCSZOR5hIjhWb
    clienteSecreto: uKCYJXAVkLY5gsWt
    maxTimeInMillis: 300000 #300000 millis = 5 minutes
  services:
    consultar-usuarios-empresas: /api/v1/colclientes/usuarios/empresas/personas
    consultar-empresa: /api/v1/colclientes/usuarios/empresas
    crear-empresa: /api/v1/colclientes/usuarios/empresas
    crear-usuario-empresa: /api/v1/colclientes/usuarios/personas/empresas
colsubsidio:
  elasticSearch:
    index: api-prices
    type: api-azure
logging:
  level:
    api: TRACE
    web: DEBUG
  console: true
swagger:
  url: http://localhost:8080/v1.0/swagger-ui/index.html#/
security:
  secret-aes: $C@lcl13n!es#$CR
  api-key: 3c4504c4-72b2-11ee-b962-0242ac120002
mail:
  url: http://40.117.63.112/utilidades/email/api/v1/email
  method: POST
  copy:
  headers: "{'Authorization': 'YXNlc3Zpcmw='}"
  replyHidden: diannys.granadillo@gtcloud.com.co
  url-colsubsidio:
    colsubsidio-empresas:  www.colsubsidio.com/empresas
    ayuda-afiliacion-grupo-familiar:  https://ayuda.colsubsidio.com/como-afilio-grupo-familiar
    ayuda-subsidio-familiar: https://ayuda.colsubsidio.com/como-solicito-mi-subsidio-familiar
    ayuda-afiliacion-colaboradores: https://ayuda.colsubsidio.com/como-afilio-a-mis-colaboradores
  mail-colsubsidio:
    correo-afiliaciones: operadorafiliaciones1@colsubsidio.com
    correo_novedades-afiliacion: novedadesafiliaciones.linea@colsubsidio.com
notification:
  email:
    url: https://app-tra-email-sender-api-develop.azurewebsites.net
    path: /v1.0/mail