CREATE TABLE IF NOT EXISTS prices (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
brand_id BIGINT NOT NULL,
start_date TIMESTAMP NOT NULL,
end_date TIMESTAMP NOT NULL,
price_list BIGINT NOT NULL,
product_id BIGINT NOT NULL,
priority INTEGER NOT NULL,
price DECIMAL(10, 2) NOT NULL,
curr VARCHAR(5) NOT NULL
);